{ statuses: 
   [ { metadata: [Object],
       created_at: 'Sun Nov 02 01:19:00 +0000 2014',
       id: 528717882318786560,
       id_str: '528717882318786560',
       text: 'RT @jcoz1968: NodeJS: Building Apps with Node.js Jump Start http://t.co/3qFrQFvEpv #nodejs #javascript',
       source: '<a href="http://www.blaccspot.com" rel="nofollow">JavaScript Digest</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 1,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 01:18:22 +0000 2014',
       id: 528717722692382700,
       id_str: '528717722692382720',
       text: 'RT @jaganbhathri: Introduction to NodeJS, A SSJS: Part III – When [NOT] to Use... http://t.co/5mu1AYEHEZ',
       source: '<a href="http://www.codex-sa.com" rel="nofollow">App home followers</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 3,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 01:18:06 +0000 2014',
       id: 528717656107802600,
       id_str: '528717656107802624',
       text: 'NodeJS: Building Apps with Node.js Jump Start http://t.co/3qFrQFvEpv #nodejs #javascript',
       source: '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweet_count: 1,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 01:10:34 +0000 2014',
       id: 528715757711286300,
       id_str: '528715757711286272',
       text: 'RT @jpetazzo: OH: "@docker is a condom between nodejs and your computer"',
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 37,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 01:07:05 +0000 2014',
       id: 528714880900005900,
       id_str: '528714880900005888',
       text: 'RT @Nubelo: "Cómo utilizar Grunt" por Andrés Rondán #grunt un automatizador de tareas para #nodejs.Quieres saber de qué se trata? http://t.…',
       source: '<a href="http://www.blaccspot.com" rel="nofollow">JavaScript Digest</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 3,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'es' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 01:02:42 +0000 2014',
       id: 528713777110200300,
       id_str: '528713777110200320',
       text: 'RT @jaganbhathri: Introduction to NodeJS, A SSJS: Part III – When [NOT] to Use... http://t.co/5mu1AYEHEZ',
       source: '<a href="http://simbasystems.com" rel="nofollow">javascriptdigest</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 3,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 01:02:24 +0000 2014',
       id: 528713704410734600,
       id_str: '528713704410734592',
       text: 'RT @Wraithan: Hey, so does anyone wanna be my manager? No really, we are hiring a manager for the @newrelic #nodejs team: http://t.co/ul4gT…',
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 8,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 01:00:23 +0000 2014',
       id: 528713196782501900,
       id_str: '528713196782501889',
       text: 'RT @Nubelo: "Cómo utilizar Grunt" por Andrés Rondán #grunt un automatizador de tareas para #nodejs.Quieres saber de qué se trata? http://t.…',
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 3,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'es' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 00:59:33 +0000 2014',
       id: 528712986354282500,
       id_str: '528712986354282497',
       text: 'RT @eiriklv: Shoestring - A lightweight alternative to jQuery :-) https://t.co/52GRIfQi2x #javascript #nodejs',
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 5,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 00:55:54 +0000 2014',
       id: 528712069219352600,
       id_str: '528712069219352576',
       text: 'someone solve this problem, mongoose authentication http://t.co/VGVBgHYb0e #node.js #mongoose @mongodb',
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweet_count: 0,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 00:50:03 +0000 2014',
       id: 528710594275586050,
       id_str: '528710594275586048',
       text: 'RT @jaganbhathri: Introduction to NodeJS, A SSJS: Part III – When [NOT] to Use... http://t.co/5mu1AYEHEZ',
       source: '<a href="http://ameanmagazine.blogspot.com" rel="nofollow">A Mean Magazine Bot</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 3,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 00:50:00 +0000 2014',
       id: 528710582677934100,
       id_str: '528710582677934080',
       text: 'Introduction to NodeJS, A SSJS: Part III – When [NOT] to Use... http://t.co/5mu1AYEHEZ',
       source: '<a href="http://www.c-sharpcorner.com" rel="nofollow">CSharpcorner</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweet_count: 3,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 00:49:44 +0000 2014',
       id: 528710516709920800,
       id_str: '528710516709920768',
       text: 'RT @_clarkio: Just built a hello world app using the MEAN stack thanks to @josepheames course on @pluralsight http://t.co/xjQFyEPCbY',
       source: '<a href="http://simbasystems.com" rel="nofollow">javascriptdigest</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 1,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 00:49:19 +0000 2014',
       id: 528710410145234940,
       id_str: '528710410145234944',
       text: 'RT @insta_arduino: http://t.co/yO7RQbSWem - #arduino #johnnyfive #nodeBots #nodeJS by gorrotowi @ http://t.co/YWjTfg4HBy http://t.co/yUcnEE…',
       source: '<a href="http://www.blaccspot.com" rel="nofollow">JavaScript Digest</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 4,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'pl' },
     { metadata: [Object],
       created_at: 'Sun Nov 02 00:49:18 +0000 2014',
       id: 528710404499705860,
       id_str: '528710404499705856',
       text: 'RT @AndyHaskell2013: OneBlueLenz: #JavaScript promise libraries are cool but if we use em I\'ll miss drawing stick figures surfing on #nodej…',
       source: '<a href="http://www.blaccspot.com" rel="nofollow">JavaScript Digest</a>',
       truncated: false,
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       retweet_count: 2,
       favorite_count: 0,
       entities: [Object],
       favorited: false,
       retweeted: false,
       lang: 'en' } ],
  search_metadata: 
   { completed_in: 0.016,
     max_id: 528717882318786560,
     max_id_str: '528717882318786560',
     next_results: '?max_id=528710404499705855&q=nodejs%20OR%20%23node&include_entities=1',
     query: 'nodejs+OR+%23node',
     refresh_url: '?since_id=528717882318786560&q=nodejs%20OR%20%23node&include_entities=1',
     count: 15,
     since_id: 0,
     since_id_str: '0' } }
